id: QmRV73R4ZyBXjnanoWrCJH5D57pGtQMeLuNoHmUiZ3Toxy
description: Returns pong to a ping over http
tags: []
source: .
trigger:
    type: https
    method: GET
    paths:
        - /ping
domains:
    - GeneratedDomain
execution:
    timeout: 5s
    memory: 10MB
    call: ping
